import os
import math
import json
import torch

import numpy as np

from .observation_utils import (
    get_default_obs_camera_name,
    world_to_screen,
    PointCloudObservationWrapper,
    world_to_screen_idx
)


def convert_point_to_grid_index(point, bounds_min=(-8, -8, -8), bounds_max=(8, 8, 8), grid=1000):
    bounds_min = np.array(bounds_min)
    bounds_max = np.array(bounds_max)
    point = np.array(point)
    normalized = (point - bounds_min) / (bounds_max - bounds_min)
    index = (normalized * (grid - 1)).astype(int)
    index = np.clip(index, 0, grid - 1)
    return tuple(index)


class CostMapHandler:

    def __init__(self, costmaps: dict):
        """
        Initialize the costmap handler for each scene.
        The parameter `costmaps` is a dictionary where the keys are subtask IDs,
        and the values are the costmap information generated by CostMapCreator
        (including affordance and collision information).
        For each subtask, initialize a visited_cost array and a total_visits counter,
        and also create a global step counter (global_step).
        """
        self.costmaps = {}
        self._grid_size = 800
        self._bounds_min = (-4, -4, 0)
        self._bounds_max = (4, 4, 4)
        self._ucb_factor = 0
        for key, costmap_info in costmaps.items():
            # Initialize visited_cost and total_visits for each subtask.
            self.costmaps[key] = {
                "info": costmap_info,
                "visited_cost": np.zeros(
                    (self._grid_size, self._grid_size, self._grid_size)),
                "total_visits": 0
            }
        self.global_step = 0
        self._reset_every = 2000
    
    def __len__(self):
        return len(self.costmaps)

    def eval_cost(self, subtask_id, point, env, obs_camera_name, idx):
        """
        Compute the cost of a candidate action without updating visited_cost and total_visits.
        Returns a tuple (cand_cost, grid_idx).
        """
        if subtask_id not in self.costmaps:
            return None, None
        data = self.costmaps[subtask_id]
        costmap_info = data["info"]
        base_cost, affordance_points = CostMapCreator.eval_cost_map(
            point, costmap_info, env, obs_camera_name, idx)
        grid_idx = convert_point_to_grid_index(
            point, bounds_min=self._bounds_min,
            bounds_max=self._bounds_max, grid=self._grid_size)
        # import ipdb; ipdb.set_trace()
        visited = data["visited_cost"][grid_idx]
        # ucb = math.sqrt(math.log(data["total_visits"] + 1) / (visited + 1))
        # Assigns higher cost to frequently visited points.
        ucb_penalty = self._ucb_factor * (math.sqrt(visited) + 1e-5)
        cand_cost = base_cost + ucb_penalty
        return cand_cost, grid_idx, affordance_points

    def apply_update(self, subtask_id, grid_idx):
        """
        Update the visited_cost and total_visits for the specified subtask and grid index,
        and check whether the global step counter needs to be reset.
        """
        if subtask_id not in self.costmaps:
            return
        data = self.costmaps[subtask_id]
        data["visited_cost"][grid_idx] += 1
        data["total_visits"] += 1
        self.global_step += 1
        if self.global_step >= self._reset_every:
            for d in self.costmaps.values():
                d["visited_cost"] = np.zeros(
                    (self._grid_size, self._grid_size, self._grid_size)
                )
                d["total_visits"] = 0
            self.global_step = 0

    def get_costmap_info(self, subtask_id):
        """
        Retrieve the costmap information for the specified subtask.
        """
        if subtask_id in self.costmaps:
            return self.costmaps[subtask_id]["info"]
        return None


class CostMapCreator:

    def __init__(self, costmap_path=None, obs_camera_name=None):
        self.costmap_path = costmap_path
        self.obs_camera_name = obs_camera_name

    def create_costmaps(self, env, env_reset_options, traj_data, idx, norm_factor=1000):
        """Create cost map based on Gemini 2 point trajectories

        Args:
            env: A gym environment
            env_reset_options: A dictionary of options for the environment reset
            traj_data: A list of dictionaries, each containing the following keys
                - point: a tuple of normalized (y, x) coordinates
                - label: an integer indicating the index of the trajectory point
                - task: a string indicating the task of the trajectory point
                - approach_object: a boolean indicating whether the agent is
                    approaching an object
                
                Check exprl/prompts/planner.txt for more details
        """
        # wrapped_env = PointCloudObservationWrapper(env.unwrapped)
        obs, _, _, xyzw = env.reset(**env_reset_options)

        if self.obs_camera_name is None:
            camera_name = get_default_obs_camera_name(env)
        else:
            camera_name = self.obs_camera_name
        image = obs[idx]
        h, w = image.shape[:2]

        xyzw = xyzw.detach().cpu().numpy()
        xyzw = xyzw[idx]

        all_costmaps = {}
        for traj_point in traj_data:
            y_norm, x_norm = traj_point["point"]
            label = int(traj_point["label"])

            scaled_x = int(x_norm / norm_factor * w)
            scaled_y = int(y_norm / norm_factor * h)


            world_3d = xyzw[scaled_y, scaled_x, :4]

            if traj_point["approach_object"]:
                affordance_points = world_3d[..., :3].reshape(1, 3)
                affordance_types = "object"
            else:
                affordance_points = np.array([scaled_x, scaled_y]).reshape(1, 2)
                affordance_types = "motion"
            # import ipdb; ipdb.set_trace()

            cost_map_info = {
                "affordance_points": affordance_points,
                "affordance_types": affordance_types,
                "collision_points": [[]], 
                "collision_thresholds": np.ones((0,)) * 1e-3,  
                "task": traj_point.get("task", ""),
                "grasp_subtask_switch": traj_point.get("grasp_subtask_switch", False),
            }
            all_costmaps[label] = cost_map_info

            if self.costmap_path:
                costmap_path = os.path.join(self.costmap_path, f"cost_map_{label}.npy")
                np.save(costmap_path, cost_map_info)
                print(f"[Label {label}] cost_map saved to: {costmap_path}")

        print("All trajectory points processed. Exiting.")

        return all_costmaps

    @staticmethod
    def eval_cost_map(points, cost_map_info, env, obs_camera_name, env_idx):
        """Generate a scoring function that returns the cost of an input 3d point,
        given the affordance and collision points stored in the cost_map_info

        Args:
            points: a np array of shape [D1, ..., DN, 3], indicating 3D positions
            cost_map_info: a diction with the following key-value pairs
                - affordance_points: a float np array of shape [num_points, 3]
                - collision_points: a float np array of shape [num_points, 3]
                - collision_thresholds: a float np array of shape [num_points]
        
        Returns:
            A np array of shape shape [D1, ..., DN], indicating the cost of
            each 3D position
        """
        

        
        max_cost = 1000

        reshaped_points = points.reshape(-1, 3)

        affordance_points = None


        # Compute affordance
        if cost_map_info["affordance_types"] == "object":
            # check affordance_points
            affordance_points = cost_map_info["affordance_points"].reshape(-1, 3)
            if isinstance(affordance_points, torch.Tensor):
                affordance_points = affordance_points.detach().cpu().numpy()
            affordance_distance = np.linalg.norm(
                reshaped_points[:, None] - affordance_points[None, :], axis=-1)
            # affordance_points = world_to_screen_idx(
            #     env, obs_camera_name, affordance_points.reshape(-1, 3), env_idx
            # )
            # if env_idx > 31:
            #     import ipdb; ipdb.set_trace()
        elif cost_map_info["affordance_types"] == "motion":
            affordance_points = cost_map_info["affordance_points"].reshape(-1, 2)
            reshaped_points_2d = world_to_screen_idx(
                env, obs_camera_name, reshaped_points.reshape(-1, 3), env_idx
            )
            affordance_distance = np.linalg.norm(
                reshaped_points_2d[:, None] - affordance_points[None, :], axis=-1)
        # find minimum affordance for each input position
        cost = affordance_distance.min(axis=-1)
        collision_points = np.array(cost_map_info["collision_points"])
        if collision_points.size == 0:
            collision_points = np.empty((0, 3))
        else:
            collision_points = collision_points.reshape(-1, 3)
        collision_thresholds = np.array(cost_map_info["collision_thresholds"]).reshape(-1)

        # Compute collision cost
        collision_distance = np.linalg.norm(
            reshaped_points[:, None] - collision_points[None, :], axis=-1)
        collision = (collision_distance <= collision_thresholds).any(axis=-1)

        # Assign max_cost when collision happens
        cost[collision] = max_cost


        if points.ndim == 1:
            return cost.item(), affordance_points
        else:
            return cost.reshape(points.shape[:-1]), affordance_points
